steps:
- task: MSBuild@1
  displayName: Build the database project
  inputs:
    solution: samples/databases/wide-world-importers/wwi-ssdt/wwi-ssdt/WideWorldImporters.sqlproj
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: samples/databases/wide-world-importers/wwi-ssdt/wwi-ssdt/bin/Debug/WideWorldImporters.dacpac'
    ArtifactName: theDacpac
    ArtifactType: Container


